"""initial schema

Revision ID: f57430ebd3bf
Revises: 
Create Date: 2026-10-06 22:27:11.075172

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f57430ebd3bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('Attendee', 'Organizer', 'Admin', 'SuperAdmin', name='user_role', native_enum=False, length=20), server_default='Admin', nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='admin_status'), server_default='pending', nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role <> 'SuperAdmin'", name=op.f('ck_admins_role_never_superadmin')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['admins.id'], name=op.f('fk_admins_approved_by_id_admins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('email', name='uq_admins_email')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=False)
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), server_default='No bio available', nullable=False),
    sa.Column('image', sa.String(length=500), server_default='', nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('instagram', sa.String(length=500), nullable=True),
    sa.Column('twitter', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('birth_date <= CURRENT_DATE', name=op.f('ck_artists_not_future')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists'))
    )
    op.create_index(op.f('ix_artists_artist_name'), 'artists', ['artist_name'], unique=False)
    op.create_index(op.f('ix_artists_genre'), 'artists', ['genre'], unique=False)
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('profile_img', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mobile_number IS NULL OR mobile_number ~ '^\\d{10}$'", name=op.f('ck_attendees_mobile_10_digits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendees')),
    sa.UniqueConstraint('email', name='uq_attendees_email'),
    sa.UniqueConstraint('username', name='uq_attendees_username')
    )
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('profile_img', sa.String(length=500), server_default='', nullable=False),
    sa.Column('cover_image', sa.String(length=500), server_default='', nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), server_default='0', nullable=False),
    sa.Column('event_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.CheckConstraint("mobile_number IS NULL OR mobile_number ~ '^\\d{10}$'", name=op.f('ck_organizers_mobile_10_digits')),
    sa.CheckConstraint('char_length(about) <= 300', name=op.f('ck_organizers_about_max_300')),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name=op.f('ck_organizers_rating_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizers')),
    sa.UniqueConstraint('email', name='uq_organizers_email'),
    sa.UniqueConstraint('username', name='uq_organizers_username')
    )
    op.create_table('superadmin_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_superadmin_whitelist')),
    sa.UniqueConstraint('email', name='uq_superadmin_whitelist_email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.Enum('public', 'private', name='event_type'), server_default='public', nullable=False),
    sa.Column('tickets_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('max_attendees', sa.Integer(), nullable=False),
    sa.Column('current_attendees', sa.Integer(), server_default='0', nullable=False),
    sa.Column('banner', sa.String(length=500), server_default='', nullable=False),
    sa.Column('speakers', postgresql.ARRAY(sa.String(length=150)), server_default='{}', nullable=False),
    sa.Column('services', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('sponsors', postgresql.ARRAY(sa.String(length=200)), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'cancelled', 'completed', name='event_status'), server_default='pending', nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('roar', sa.String(length=500), server_default='Event not started yet', nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_attendees <= max_attendees', name=op.f('ck_events_within_capacity')),
    sa.CheckConstraint('current_attendees >= 0', name=op.f('ck_events_current_attendees_non_negative')),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_events_end_after_start')),
    sa.CheckConstraint('max_attendees > 0', name=op.f('ck_events_max_attendees_positive')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_events_price_non_negative')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['admins.id'], name=op.f('fk_events_approved_by_id_admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['admins.id'], name=op.f('fk_events_cancelled_by_id_admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], name=op.f('fk_events_organizer_id_organizers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('event_name', name='uq_events_event_name')
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_index('ix_events_status_start_date', 'events', ['status', 'start_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient_kind', sa.Enum('Organizer', 'Attendee', 'Admin', name='notification_recipient_kind'), nullable=False),
    sa.Column('organizer_recipient_id', sa.Integer(), nullable=True),
    sa.Column('attendee_recipient_id', sa.Integer(), nullable=True),
    sa.Column('admin_recipient_id', sa.Integer(), nullable=True),
    sa.Column('sender_kind', sa.Enum('EventSphere', 'Organizer', 'Attendee', 'Admin', name='notification_sender'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(recipient_kind = 'Organizer' AND organizer_recipient_id IS NOT NULL AND attendee_recipient_id IS NULL AND admin_recipient_id IS NULL) OR (recipient_kind = 'Attendee' AND attendee_recipient_id IS NOT NULL AND organizer_recipient_id IS NULL AND admin_recipient_id IS NULL) OR (recipient_kind = 'Admin' AND admin_recipient_id IS NOT NULL AND organizer_recipient_id IS NULL AND attendee_recipient_id IS NULL)", name=op.f('ck_notifications_single_recipient_matches_kind')),
    sa.ForeignKeyConstraint(['admin_recipient_id'], ['admins.id'], name=op.f('fk_notifications_admin_recipient_id_admins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attendee_recipient_id'], ['attendees.id'], name=op.f('fk_notifications_attendee_recipient_id_attendees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_recipient_id'], ['organizers.id'], name=op.f('fk_notifications_organizer_recipient_id_organizers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_admin_recipient_id'), 'notifications', ['admin_recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_attendee_recipient_id'), 'notifications', ['attendee_recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_organizer_recipient_id'), 'notifications', ['organizer_recipient_id'], unique=False)
    op.create_index('ix_notifications_recipient_created', 'notifications', ['recipient_kind', 'created_at'], unique=False)
    op.create_table('organizer_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('char_length(text) <= 200', name=op.f('ck_organizer_achievements_max_200_chars')),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], name=op.f('fk_organizer_achievements_organizer_id_organizers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizer_achievements'))
    )
    op.create_index(op.f('ix_organizer_achievements_organizer_id'), 'organizer_achievements', ['organizer_id'], unique=False)
    op.create_table('organizer_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('months >= 0 AND months <= 11', name=op.f('ck_organizer_experience_months_range')),
    sa.CheckConstraint('years >= 0 AND years <= 100', name=op.f('ck_organizer_experience_years_range')),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], name=op.f('fk_organizer_experience_organizer_id_organizers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizer_experience'))
    )
    op.create_index(op.f('ix_organizer_experience_organizer_id'), 'organizer_experience', ['organizer_id'], unique=False)
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], name=op.f('fk_event_registrations_attendee_id_attendees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_registrations_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_registrations')),
    sa.UniqueConstraint('event_id', 'attendee_id', name='uq_registrations_event_attendee')
    )
    op.create_index(op.f('ix_event_registrations_attendee_id'), 'event_registrations', ['attendee_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.String(length=32), nullable=False),
    sa.Column('secret_code', sa.String(length=32), nullable=False),
    sa.Column('qr_code_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], name=op.f('fk_tickets_attendee_id_attendees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_tickets_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('booking_id', name='uq_tickets_booking_id'),
    sa.UniqueConstraint('event_id', 'attendee_id', name='uq_tickets_event_attendee')
    )
    op.create_index(op.f('ix_tickets_attendee_id'), 'tickets', ['attendee_id'], unique=False)
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_attendee_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_attendee_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    op.drop_index(op.f('ix_organizer_experience_organizer_id'), table_name='organizer_experience')
    op.drop_table('organizer_experience')
    op.drop_index(op.f('ix_organizer_achievements_organizer_id'), table_name='organizer_achievements')
    op.drop_table('organizer_achievements')
    op.drop_index('ix_notifications_recipient_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_organizer_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_attendee_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_admin_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_events_status_start_date', table_name='events')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    op.drop_table('superadmin_whitelist')
    op.drop_table('organizers')
    op.drop_table('attendees')
    op.drop_index(op.f('ix_artists_genre'), table_name='artists')
    op.drop_index(op.f('ix_artists_artist_name'), table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###